language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
  - make deps

script: 
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken WypIEWKIuCiNZYRfZstlsDvmNNhxyH8Fu
